/* Generated By:JavaCC: Do not edit this line. DesignParserTokenManager.java */
package edu.byu.ece.rapidSmith.design.parser;
import java.util.ArrayList;
import java.util.HashMap;
import edu.byu.ece.rapidSmith.device.*;
import edu.byu.ece.rapidSmith.design.*;
import edu.byu.ece.rapidSmith.util.*;

/** Token Manager. */
public class DesignParserTokenManager implements DesignParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x40L) != 0L)
            return 13;
         if ((active0 & 0xfffff9e000L) != 0L)
         {
            jjmatchedKind = 40;
            return 14;
         }
         if ((active0 & 0x80L) != 0L)
         {
            jjmatchedKind = 40;
            return 5;
         }
         if ((active0 & 0x61e00L) != 0L)
            return 14;
         return -1;
      case 1:
         if ((active0 & 0xfffffe0000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 1;
            return 14;
         }
         if ((active0 & 0x1e080L) != 0L)
            return 14;
         return -1;
      case 2:
         if ((active0 & 0xffff800000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 2;
            return 14;
         }
         if ((active0 & 0x7e0000L) != 0L)
            return 14;
         return -1;
      case 3:
         if ((active0 & 0x7ff8000000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 3;
            }
            return 14;
         }
         if ((active0 & 0x8007800000L) != 0L)
            return 14;
         return -1;
      case 4:
         if ((active0 & 0xffe0000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 4;
            return 14;
         }
         if ((active0 & 0x18000000L) != 0L)
            return 14;
         return -1;
      case 5:
         if ((active0 & 0xe200000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 5;
            return 14;
         }
         if ((active0 & 0x1de0000000L) != 0L)
            return 14;
         return -1;
      case 6:
         if ((active0 & 0xe200000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 6;
            return 14;
         }
         return -1;
      case 7:
         if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 7;
            return 14;
         }
         if ((active0 & 0xe000000000L) != 0L)
            return 14;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 34:
         return jjStartNfaWithStates_0(0, 6, 13);
      case 44:
         return jjStopAtPos(0, 8);
      case 45:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 46:
         return jjStartNfaWithStates_0(0, 9, 14);
      case 58:
         return jjStartNfaWithStates_0(0, 10, 14);
      case 59:
         return jjStartNfaWithStates_0(0, 11, 14);
      case 61:
         return jjMoveStringLiteralDfa1_0(0xe000L);
      case 92:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x100000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x1400000000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x200000000L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x80080000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x800c000000L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x800000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x32200000L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x6000000000L);
      case 118:
         jjmatchedKind = 12;
         return jjMoveStringLiteralDfa1_0(0x60000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x1000000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 34:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(1, 7, 14);
         break;
      case 45:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(1, 14, 14);
         break;
      case 61:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(1, 13, 14);
         break;
      case 62:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(1, 15, 14);
         else if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(1, 16, 14);
         break;
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L);
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x400400000L);
      case 102:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x1200000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0xe20c080000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x152800000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x1080000000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x20800000L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L);
      case 99:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(2, 17, 14);
         break;
      case 100:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(2, 18, 14);
         else if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(2, 19, 14);
         return jjMoveStringLiteralDfa3_0(active0, 0x300000000L);
      case 103:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(2, 20, 14);
         break;
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L);
      case 112:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(2, 21, 14);
         return jjMoveStringLiteralDfa3_0(active0, 0x2008000000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x8404000000L);
      case 116:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(2, 22, 14);
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000L);
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      case 100:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(3, 23, 14);
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000L);
      case 101:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 14);
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x408000000L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000L);
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000L);
      case 116:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(3, 25, 14);
         else if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x180000000L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0xa000000000L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x1060000000L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000L);
      case 110:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 14);
         return jjMoveStringLiteralDfa5_0(active0, 0x4080000000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000L);
      case 114:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(4, 28, 14);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000L);
      case 100:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 29, 14);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(5, 30, 14);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(5, 31, 14);
         return jjMoveStringLiteralDfa6_0(active0, 0x4200000000L);
      case 101:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(5, 32, 14);
         break;
      case 110:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(5, 34, 14);
         else if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(5, 35, 14);
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000L);
      case 114:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 36, 14);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000L);
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x6000000000L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 100:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 37, 14);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 38, 14);
         break;
      case 101:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 39, 14);
         break;
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(8, 33, 14);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 13;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0xffffeffaffffd9ffL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     jjCheckNAddTwoStates(3, 4);
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(0, 2);
                  if (curChar == 35)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               case 13:
                  if ((0xfffffffbffffd9ffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 34)
                  {
                     if (kind > 41)
                        kind = 41;
                  }
                  break;
               case 5:
                  if ((0xffffeffaffffd9ffL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     jjCheckNAddTwoStates(3, 4);
                  }
                  else if (curChar == 32)
                  {
                     if (kind > 40)
                        kind = 40;
                     jjCheckNAddTwoStates(3, 4);
                  }
                  else if (curChar == 34)
                  {
                     if (kind > 40)
                        kind = 40;
                     jjCheckNAddTwoStates(3, 4);
                  }
                  break;
               case 14:
               case 3:
                  if ((0xffffeffaffffd9ffL & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddTwoStates(3, 4);
                  break;
               case 1:
                  if ((0xfffffffffffffbffL & l) != 0L)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               case 2:
                  if (curChar == 10)
                     kind = 5;
                  break;
               case 6:
                  if (curChar != 32)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddTwoStates(3, 4);
                  break;
               case 7:
               case 11:
                  if (curChar == 34)
                     jjCheckNAddStates(0, 2);
                  break;
               case 8:
                  if ((0xfffffffbffffd9ffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 9:
                  if (curChar == 34 && kind > 41)
                     kind = 41;
                  break;
               case 12:
                  if (curChar == 32)
                     jjCheckNAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddTwoStates(3, 4);
                  if (curChar == 92)
                     jjAddStates(3, 4);
                  break;
               case 13:
                  jjCheckNAddStates(0, 2);
                  if (curChar == 92)
                     jjAddStates(5, 6);
                  break;
               case 5:
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddTwoStates(3, 4);
                  if (curChar == 92)
                     jjAddStates(3, 4);
                  break;
               case 14:
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddTwoStates(3, 4);
                  if (curChar == 92)
                     jjAddStates(3, 4);
                  break;
               case 1:
                  jjAddStates(7, 8);
                  break;
               case 3:
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddTwoStates(3, 4);
                  break;
               case 4:
                  if (curChar == 92)
                     jjAddStates(3, 4);
                  break;
               case 8:
                  jjCheckNAddStates(0, 2);
                  break;
               case 10:
                  if (curChar == 92)
                     jjAddStates(5, 6);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 3:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddTwoStates(3, 4);
                  break;
               case 13:
               case 8:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 5:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddTwoStates(3, 4);
                  break;
               case 14:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddTwoStates(3, 4);
                  break;
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(7, 8);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 13 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   8, 9, 10, 5, 6, 11, 12, 1, 2, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, "\42", "\134\42", "\54", "\56", "\72", 
"\73", "\166", "\75\75", "\75\55", "\75\76", "\55\76", "\166\143\143", 
"\166\144\144", "\147\156\144", "\143\146\147", "\160\151\160", "\156\145\164", 
"\154\157\141\144", "\167\151\162\145", "\160\157\162\164", "\151\156\163\164", 
"\151\156\160\151\156", "\160\157\167\145\162", "\160\154\141\143\145\144", 
"\142\157\156\144\145\144", "\147\162\157\165\156\144", "\155\157\144\165\154\145", 
"\145\156\144\155\157\144\165\154\145", "\144\145\163\151\147\156", "\157\165\164\160\151\156", 
"\144\162\151\166\145\162", "\165\156\160\154\141\143\145\144", "\165\156\142\157\156\144\145\144", 
"\151\156\163\164\141\156\143\145", null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x3ffffffffc1L, 
};
static final long[] jjtoSkip = {
   0x3eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[13];
private final int[] jjstateSet = new int[26];
protected char curChar;
/** Constructor. */
public DesignParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public DesignParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 13; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
