/* Generated By:JavaCC: Do not edit this line. DesignParserConstants.java */
package edu.byu.ece.rapidSmith.design.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DesignParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DOUBLEQUOTE = 6;
  /** RegularExpression Id. */
  int ESCAPED_DOUBLEQUOTE = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int PERIOD = 9;
  /** RegularExpression Id. */
  int COLON = 10;
  /** RegularExpression Id. */
  int SEMICOLON = 11;
  /** RegularExpression Id. */
  int VER = 12;
  /** RegularExpression Id. */
  int PIP0 = 13;
  /** RegularExpression Id. */
  int PIP1 = 14;
  /** RegularExpression Id. */
  int PIP2 = 15;
  /** RegularExpression Id. */
  int PIP3 = 16;
  /** RegularExpression Id. */
  int VCC = 17;
  /** RegularExpression Id. */
  int VDD = 18;
  /** RegularExpression Id. */
  int GND = 19;
  /** RegularExpression Id. */
  int CFG = 20;
  /** RegularExpression Id. */
  int PIP = 21;
  /** RegularExpression Id. */
  int NET = 22;
  /** RegularExpression Id. */
  int LOAD = 23;
  /** RegularExpression Id. */
  int WIRE = 24;
  /** RegularExpression Id. */
  int PORT = 25;
  /** RegularExpression Id. */
  int INST = 26;
  /** RegularExpression Id. */
  int INPIN = 27;
  /** RegularExpression Id. */
  int POWER = 28;
  /** RegularExpression Id. */
  int PLACED = 29;
  /** RegularExpression Id. */
  int BONDED = 30;
  /** RegularExpression Id. */
  int GROUND = 31;
  /** RegularExpression Id. */
  int MODULE = 32;
  /** RegularExpression Id. */
  int ENDMODULE = 33;
  /** RegularExpression Id. */
  int DESIGN = 34;
  /** RegularExpression Id. */
  int OUTPIN = 35;
  /** RegularExpression Id. */
  int DRIVER = 36;
  /** RegularExpression Id. */
  int UNPLACED = 37;
  /** RegularExpression Id. */
  int UNBONDED = 38;
  /** RegularExpression Id. */
  int INSTANCE = 39;
  /** RegularExpression Id. */
  int UNQUOTED_STRING = 40;
  /** RegularExpression Id. */
  int QUOTED_STRING = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"\\\"\"",
    "\"\\\\\\\"\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\"v\"",
    "\"==\"",
    "\"=-\"",
    "\"=>\"",
    "\"->\"",
    "\"vcc\"",
    "\"vdd\"",
    "\"gnd\"",
    "\"cfg\"",
    "\"pip\"",
    "\"net\"",
    "\"load\"",
    "\"wire\"",
    "\"port\"",
    "\"inst\"",
    "\"inpin\"",
    "\"power\"",
    "\"placed\"",
    "\"bonded\"",
    "\"ground\"",
    "\"module\"",
    "\"endmodule\"",
    "\"design\"",
    "\"outpin\"",
    "\"driver\"",
    "\"unplaced\"",
    "\"unbonded\"",
    "\"instance\"",
    "<UNQUOTED_STRING>",
    "<QUOTED_STRING>",
  };

}
